# fly.toml app configuration file generated for mk-service-backend-snowy-waterfall-1644 on 2025-08-03T17:14:16+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mk-service-backend-snowy-waterfall-1644'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
